name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: TEST_APP

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - name: format
            command: fmt
            args: --all -- --check --color always
          - name: client
            command: build
            args: --release --example client
          - name: client
            command: clippy
            args: --lib --example client -- -D warnings
          - name: server
            command: build
            args: --release --example server
          - name: server
            command: clippy
            args: --lib --example server -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
          version: 1.82.0.3
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
