name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: TEST_APP

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - name: nofeatures
            command: fmt
            args: --all -- --check --color always
          - name: nofeatures
            command: build
            args: --release
          - name: nofeatures
            command: clippy
            args: --workspace --bins --lib -- -D warnings
          - name: wifi
            command: build
            args: --release --features=wifi
          - name: wifi
            command: clippy
            args: --workspace --bins --lib --features=wifi -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
          version: 1.82.0.3
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
        env:
          WIFI_SSID: ${{ matrix.action.name == 'wifi' && 'TEST_SSID' || '' }}
          WIFI_PASSWORD: ${{ matrix.action.name == 'wifi' && 'TEST_PASSWORD' || '' }}
          HTTP_URL: ${{ matrix.action.name == 'wifi' && 'https://test.com' || '' }}
